FROM node:lts-alpine as builder
WORKDIR /app
COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# CMD ["npm", "start"]

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html
